#  Build stage to transpile TS to JS
FROM node:alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

#  Copy transpiled JS to final image
FROM nginx:latest AS production
RUN mkdir /app
COPY --from=build /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf