# Stage 1: Install dependencies and build the application
ARG NODE_VERSION=20.17.0
FROM node:${NODE_VERSION}-alpine AS build

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install development dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the TypeScript code
RUN npm run build

# Stage 2: Run the application
FROM node:${NODE_VERSION}-alpine AS production

# Set default environment variables
ARG NODE_ENV
ENV NODE_ENV=$NODE_ENV

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json from the build stage
COPY --from=build /usr/src/app/package*.json ./

# Install only production dependencies
RUN npm ci --omit=dev

# Copy only the necessary files from the build stage
COPY --from=build /usr/src/app/dist ./dist

# Set default port
ARG PORT
ENV PORT=$PORT
EXPOSE $PORT

# Start the application
CMD ["node", "dist/server.js"]